FROM node:10 as react-build

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ARG API_URL
ENV API_URL=${API_URL}

COPY . ./

RUN npm install

RUN npm build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=react-build /usr/src/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]