# base image
FROM cypress/browsers:chrome65-ff57

ARG API_URL
ENV API_URL=${API_URL}

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

COPY . ./
RUN npm install


# install cypress
RUN npm install cypress

# confirm the cypress install
RUN ./node_modules/.bin/cypress verify