FROM tiangolo/node-frontend:10 as build-stage

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

COPY . ./
RUN npm install

ARG API_URL
ENV API_URL=${API_URL}

RUN npm run build

FROM nginx:alpine
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
